### ISSUE TITLE
RuntimeError: shape '[1, 1]' is invalid for input of size 25

### ISSUE THREAD

**Issue by idan0610** [dynaroars/neuralsat#7]
Running the NeuralSAT tool with the attached ONNX network and VNNLIB specification, I get the following error:

```
Restricted license - for non-production use only - expires 2025-11-24
/home/idan0610/miniconda3/envs/neuralsat/lib/python3.10/site-packages/torch/utils/cpp_extension.py:28: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import packaging  # type: ignore[attr-defined]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/idan0610/Marabou_dev/cdcl/neuralsat/neuralsat-pt201/util/network/read_onnx.py", line 95, in _parse_onnx
    output_onnx = torch.cat([torch.from_numpy(inference_onnx(path, dummy[i].view(orig_input_shape).float().numpy())[0]).view(batched_output_shape) for i in range(batch)])
  File "/home/idan0610/Marabou_dev/cdcl/neuralsat/neuralsat-pt201/util/network/read_onnx.py", line 95, in <listcomp>
    output_onnx = torch.cat([torch.from_numpy(inference_onnx(path, dummy[i].view(orig_input_shape).float().numpy())[0]).view(batched_output_shape) for i in range(batch)])
RuntimeError: shape '[1, 1]' is invalid for input of size 25

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/idan0610/Marabou_dev/cdcl/neuralsat/neuralsat-pt201/util/network/read_onnx.py", line 128, in parse_onnx
    return _parse_onnx(path)
  File "<@beartype(util.network.read_onnx._parse_onnx) at 0x7f5309052ef0>", line 30, in _parse_onnx
  File "/home/idan0610/Marabou_dev/cdcl/neuralsat/neuralsat-pt201/util/network/read_onnx.py", line 101, in _parse_onnx
    raise OnnxConversionError
util.misc.error.OnnxConversionError
```

To reproduce:

`python3 main.py --net cls0_id45_cls1_id86.onnx --spec cls0_id45_cls1_id86.vnnlib`

Thanks for your help on this issue!

[cls0_id45_cls1_id86.zip](https://github.com/user-attachments/files/18228589/cls0_id45_cls1_id86.zip)

**Comment by hocdot** [comment]
Hi @idan0610 , 

Thanks for report bugs. 

This error happens because of a mismatch between the output shape `(1, 5)` inferred automatically from ONNX by NeuralSAT and the actual shape `(1, 25)`.

To fix this, there are 2 options:
1. Export correct information for ONNX, e.g., the final node's input shape should be  `(1, 25)` instead of `(1, 5)`

![Image](https://github.com/user-attachments/assets/0c4e8391-de92-434f-9d99-0a3922e699a4)

2. Use the latest version of NeuralSAT and override the inferred shapes by adding argument `--output_shape`
```python
python3 main.py --net cls0_id45_cls1_id86.onnx --spec cls0_id45_cls1_id86.vnnlib --output_shape 1 25
```
